Add i18n for header quote
mintyfrankie/awesomeCV-Typst-Submodule pull request #7
Opened 2023-08-11 22:10 UTC by fnuttens

Hi! Thanks for making this gorgeous template! ✨ 

I'd like to propose making use of the `languageSwitch` for the `headerQuote`.

I realize that the current behavior is to disable this field if no value is set, but I guess it is also possible with the dictionary?

2023-08-12 13:38 UTC, mintyfrankie commented
Hi @fnuttens thanks for the PR! I indeed wanted to make it i18n and was thinking about working on it over the weekend, but you've done it beautifully already :)

I am currently "en vacances" and even sure that your PR is probably LGTM, I will check it up and also update the main repository in the following days, once I get back to my desktop!

2023-08-14 22:18 UTC, mintyfrankie requested changes
Hi, please consider reverting your latest commit so that this PR only contains changes about the headerQuote function -- we will discuss changes about headerIcons in another PR!

2023-08-14 22:18 UTC, mintyfrankie commented on metadata-demo.typ
> +  //gitlab: "mintyfrankie",
I'd suggest that this PR contains only changes about making the `headerQuote` i18n -- other changes shall go to the PR #8

2023-08-14 22:18 UTC, mintyfrankie commented on metadata-demo.typ
> +)
LGTM

2023-08-14 22:18 UTC, mintyfrankie commented on template.typ
> +    gitlab: fa-gitlab(),
as above

2023-08-14 22:18 UTC, mintyfrankie commented on template.typ
> +      } else if k == "gitlab" {
as above

2023-08-14 22:18 UTC, mintyfrankie commented on template.typ
> +  [#headerQuoteStyle(languageSwitch(headerQuoteInternational))]
Do you think if it is necessary to keep the option `headerQuote` for backward compatibility or just cleaner `metadata.typ`?

Otherwise I think it is okay though since we are in `v0.1.0`.

2023-08-15 09:52 UTC, fnuttens commented
> Hi, please consider reverting your latest commit so that this PR only contains changes about the headerQuote function -- we will discuss changes about headerIcons in another PR!

Oops sorry I forgot to create a new branch for this commit… Will do!

Hope you enjoyed your vacances btw 😉

2023-08-15 10:00 UTC, fnuttens commented on template.typ
> +  [#headerQuoteStyle(languageSwitch(headerQuoteInternational))]
I think it would be cleaner to discard the simple `headerQuote`; like you said, this isn't a `v1` yet.

2023-08-16 07:34 UTC, mintyfrankie approved these changes

2023-08-16 07:34 UTC, merged

2023-08-16 07:34 UTC, mintyfrankie commented
Thanks @fnuttens. PR merged.